node {
    stage('Clone Repository') {
        git  branch: 'main', url:'https://github.com/hrushikeshpthube/JenkinsRepo.git'
    }
	
  stage('Upload to S3') {
        sh '''
        aws s3 cp .	 s3://travel-website-jenkins/ --recursive
        '''
    }
}
